### ISSUE TITLE
exercises that got me confused

### ISSUE THREAD

**Issue by vindex10** [micahkepe/vimtutor-sequel#1]
I actually only have two points:

1. Commenting and uncommenting: it would be great to explain what actually happens under the hood. Because `I#` would just prepend the line with '#' and some languages use `//` for commenting, it is not necessarily straightforward from the tutorial what my actions should be then. The same with uncommenting: `^x` would just remove the first symbol, it is not commenting related really. - maybe it would be nice to refer to the `preservim/nerdcommenter` project somewhere there :) 

2. You ask to "find and replace in the following text" but suggest using ":%s/" - which will replace in the entire file. I would select the line and use ":s" in the visual mode.

https://github.com/micahkepe/vimtutor-sequel/blob/4a6bfa3af81ac67280b0bcefa96757d463552122/vimtutor-sequel.txt#L349

**Comment by micahkepe** [comment]
Good points thank you! I will be updating the tutor as I receive more feedback this is much appreciated :)

**Comment by micahkepe** [comment]
Your suggestions have been incorporated! Check out v1.3 for the latest changes!
