### ISSUE TITLE
Constructive comments

### ISSUE THREAD

**Issue by r1cc4rdo** [micahkepe/vimtutor-sequel#10]
Thanks for VimTutor sequel!
I've just completed it and kept track of things that were confusing or awkward to me.
I've cleared all the following doubts already, but recording them here in case you find them useful.
The points below are meant as constructive suggestions. Can submit PRs, should you decide to greenlight any.

### Introduction
* could explain how to get/run vimtutor

### Lesson 10.1
* paragraph motions (used in `V}`), first non-blank `^`, reselect Visual area `gv` are neither introduced nor explained. In particular, coming from vimtutor where all g commands introduced where shorthands for "go", `gv` took me a bit by surprise.
* was confused by `=`, not understanding it expected a motion command afterwards (and therefore not understanding the difference with `==`)

### Lesson 10.2
* `:norm` is not explained anywhere, and mysterious

### Lesson 10.3
* first time verbs made of multiple keystrokes (e.g. `gu`, `gU`) are encountered across lessons 1--10, made mentally parsing the commands confusing at first.
* I would also have preferred being given generic commands in the form e.g. `gu`{motion} like `:help` does rather than specific instances, i.e. `guw`

### Lesson 11
* search and replace are already covered by lesson 4.4 of vimtutor

### Lesson 13
* could explicitly say what `nnoremap` does (for example, that it creates a mapping for normal mode). This is one of the few case in which `:help` does not help much
* in the vimscript example, got confused by why variable names had a prefix, e.g. `a:spell`

### Lesson 15.2
* was confused re: what point (5) asked me to do. I had already learned how to create macros in Lesson 12; I guess the message here was that registers can contain anything, macros included, and that in fact recording a macro uses that particular register. What I attempted to do instead was to yank the characters `qmcwHogwarts<Esc>jq` into register `"m` and then execute them as a macro XD

**Comment by micahkepe** [comment]
Thank you for the feedback! These are all good things to consider for the next release. Just to touch on a few of your points:

- Improving the explanations and command specifications are spot on and will definitely be priority for the next release(s)
- `vimtutor` installation was opted to not be covered as the sequel assumes that users have already gone through the `vimtutor` program 
- while search and replace was covered in the original program, I wanted to highlight the different options that are available for search and replace (for example with confirmations), which I believe the original did not cover

**Comment by r1cc4rdo** [comment]
Thanks for replying :)
Feel free to close this if there's no immediate next action!

**Comment by r1cc4rdo** [comment]
I looked into sending PRs, but my preferred way to amend the tutorial would be to add two new lessons before the current 10, one with advanced navigation including ```}```, ```{```, ```W```, ```B```, ```E```, ```^```, a second with advanced selection ```V```, ```^v```, ```gv``` (since I realized that ```V``` is also never covered, neither here nor in the original vimtutor).

This would require shifting all lesson numbers and feels a little too intrusive, but I can go ahead if ok with you. Otherwise, it's my suggestion to you for next version 😄

**Comment by micahkepe** [comment]
Sorry for the late response. I think instead of two new lessons it would be better to have shorter "asides" on these topics. This would keep the lesson numbers the same. Additionally, I think keeping it to 8 lessons is good for keeping the time to complete the tutor reasonable.
