### ISSUE TITLE
Vim alert me about "a plugin"may be a little isue my.

### ISSUE THREAD

**Issue by jazei-AR** [micahkepe/vimtutor-sequel#6]
sorry my no english
maybe about the vimrc you write: have I got that vimrc?
![screen](https://github.com/user-attachments/assets/34b5e5a9-ae33-4eee-a5f1-fdb42f6a82c9)

could you give me another mode to enter... without using vimrc It is just of time. be patient 
important: I see you vimtutor II
regards!

**Comment by micahkepe** [comment]
Hello, please try this and see if it works.

Use the -u option to specify the custom vimrc and the -U NONE option to avoid loading any user-specific gvimrc:
```bash
vim -u vimtutor-sequel.vimrc -U NONE vimtutor-sequel-copy.txt
```
---
Usa la opción -u para especificar el archivo vimrc personalizado y la opción -U NONE para evitar cargar cualquier archivo gvimrc específico del usuario:
```bash
vim -u vimtutor-sequel.vimrc -U NONE vimtutor-sequel-copy.txt
```
