### ISSUE TITLE
Can I get Lesson 1~7 ?

### ISSUE THREAD

**Issue by june5079** [micahkepe/vimtutor-sequel#7]
Hi, pals

Thx for making awesome tutorials. 
I would like to start with Lesson 1 but can't find that (start with lesson 8)

Can I get full lessons?

**Comment by micahkepe** [comment]
Hello! 

The tutor actually intentionally starts at Lesson 8 since the original vimtutor ends at Lesson 7. Sorry for any confusion, let me know if you have any other questions!

**Comment by june5079** [comment]
@micahkepe THX!!!!
